[project]
name = "ipmanager-django"
description = "Stand-alone IP Manager Service (Django implementation)"
version = "1.0.0-dev"
dependencies = [
    "django",
    "django-umd-lib-style",
    "django-extensions",
    "django-environ",
    "binarytree",
    "djangosaml2",
    "urlobject",
    "waitress~=3.0",
    "click~=8.1",
    "whitenoise~=6.9"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-django",
    "ruff",
]
prod = [
    "psycopg[binary]"
]

[project.scripts]
ipmanager = "ipmanager.server:run"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ipmanager.settings"

[tool.ruff.format]
# Prefer single quotes over double quotes.
quote-style = "single"
exclude = ["manage.py"]
